### ISSUE TITLE
Stop logging to the syslog

### ISSUE THREAD

**Issue by SvenGWK** [MaxBec/hassio-diyHue#41]
If this is a stupid question, I apologize in advance. I don't have much knowledge about docker...

The integration floods /var/log/syslog with this information even if debug is turned off:

```
A
{'alert': 'select',
 'bri': 171,
 'colormode': 'xy',
 'ct': 500,
 'mode': 'homeautomation',
 'on': False,
 'reachable': False,
 'xy': [0.599, 0.382]}
A
{'alert': 'select',
 'bri': 166,
 'colormode': 'xy',
 'ct': 500,
 'mode': 'homeautomation',
 'on': False,
 'reachable': False,
 'xy': [0.599, 0.382]}
```
The log file is already over 100Mb after one day.

I tried

```
logger:
  default: critical
  logs:
    custom_component.590f8686_diyhue-beta-branch: critical
```
in configuration.yaml, but without success.

The container seems to be configured for logging to the syslog, right?

```
docker inspect -f '{{.HostConfig.LogConfig.Type}}' addon_590f8686_diyhue-beta-branch
journald
```

How can I turn this off?
